### ISSUE TITLE
Add check to make sure that the user is inside the guild

### ISSUE THREAD

**Issue by Muirrum** [da-stoi/herder#1]
User auth should have a check to make sure that the authenticated user is a member of the configured discord guild, to prevent spam and abuse

**Comment by da-stoi** [comment]
That's a great way to do that, thanks!
At the moment I am hoping that people don't share the link and random people don't join. If that does become an issue, or I have spare time, I will definitely implement that.

**Comment by da-stoi** [comment]
Added in b563b067e9f0043e9f666d1880303a70c31dcb81.
