### ISSUE TITLE
Allow selecting multiple pronoun values on Search page?

### ISSUE THREAD

**Issue by samollari** [da-stoi/herder#4]
It'd be nice to be able to see all matches on the Search page irrespective of their pronouns.
The values could be passed like so:
**one selection**
> - [x] He/Him
> - [ ] She/Her
> - [ ] They/Them

returns  `he`

**multiple selections**
> - [x] He/Him
> - [ ] She/Her
> - [x] They/Them

returns `he,they`

and the passed strings could be parsed with a simple `value.split(',')` and queried individually or with a union? (I don't really know how database stuff works)

**Comment by da-stoi** [comment]
Great idea! Just added it in fb69e2ac43e36197b7857525f6168d73092c91dc. 

Your `value.split(",")` was a great idea! The values are just passed through in the query parameters of the [/match](https://github.com/da-stoi/herder#match) endpoint. Example: `he,she` or `she,they`. Of course just a single pronoun still works like it used to.
